# Generated by Django 4.2.2 on 2023-07-03 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_backend.brand')),
            ],
            options={
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_backend.state')),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('version', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('mileage', models.IntegerField()),
                ('image', models.CharField(max_length=50)),
                ('promoted', models.BooleanField()),
                ('financing', models.BooleanField()),
                ('color', models.CharField(max_length=50)),
                ('fuel', models.CharField(max_length=50)),
                ('observation', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_backend.brand')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_backend.city')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_backend.model')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_backend.state')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
