# Generated by Django 4.2.2 on 2023-07-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
